#!/usr/bin/bash

# Already running?
if [ $(./nf-status-prod) -eq 0 ]; then
    echo 'Not Running'
    exit
fi

# Halt Falcon server
# Detach to prevent bash echo silencing and silence non-error output
fuser -k 9001/tcp > /dev/null 2>&1 < /dev/null

# Halt nginx
cd Server/nginx/ && ./stop.sh &

./nf-status-prod

