#!/usr/bin/env bash

echo -n 'Rebuilding client... '
cd Client && \
    npm install && \
    npm run build && \
    cp -r out/* ../Server/nginx/Client && \
    chmod -R o+rx ../Server/nginx/Client && \
    cd -
echo 'Done'
