#!/usr/bin/bash

# Already running?
#if [ $(./nf-status-prod) -eq 0 ]; then
#    echo 'Not Running'
#    exit
#fi

if [ "$(lsof -i :9001 | wc -l)" -ne 0 ]; then
    # Halt Falcon server
    # Detach to prevent bash echo silencing and silence non-error output
    fuser -k 9001/tcp > /dev/null 2>&1 < /dev/null
fi

if [ "$(lsof -i :9003 | wc -l)" -ne 0 ]; then
    # Halt nginx
    cd Server/nginx/ && ./stop.sh &
fi

#./nf-status-prod

