#!/usr/bin/env bash

# Clean
crontab -l | grep -v 'nf-run-prod' | crontab -

# Add
(crontab -l 2>/dev/null; echo "*/1 * * * * ""PATH=$PATH; cd $(pwd) && echo "$(pwd)" >> $(pwd)/run.log && ./nf-run-prod >> $(pwd)/run.log 2>&1 &") | crontab -

