#!/usr/bin/env bash

########################################################################
# Readme
##########################################################################
#
# Return: zero means on. 
# I'm attempting to follow unix conventions although 
# I'm not sure that's best 
# but for now 
# the goal is to get stable first and we can refine the flow later.
# 
#
##########################################################################

# Legend
# 
# 1: Something  is off
# 0: Everything is on
#

anything_off=0

echo -n 'Web server '
if [ "$(../Server/nginx/status.sh)" -eq 0 ]; then
    echo -n 'not '
    anything_off=1
fi
echo 'running'

echo -n 'Data server '
if [ -z "$(lsof -i :9001)" ]; then
    echo -n 'not '
    anything_off=1
fi
echo 'running'

echo $anything_off
exit $anything_off

## Another way of checking nginx
#echo -n 'Web server '
#if [ -z "$(lsof -i :9003)" ]; then
#    echo -n 'not '
#    anything_off=1
#fi
#echo 'running'

#
#if [ "$( (lsof -i :9001 | wc -l; lsof -i :9003 | wc -l ) | wc -l )" -ne "2" ];
#then
#    echo 0
#else
#    echo bar
#fi
#
#if [ ! -z "$(lsof -i :9001,9003)" ]; then 
#    echo 1
#else
#    echo 0
#fi
